"""empty message

Revision ID: 2f44fe6e73f0
Revises: 
Create Date: 2018-10-08 00:18:14.082723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f44fe6e73f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article', sa.String(length=700), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newstopic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idNews', sa.Integer(), nullable=False),
    sa.Column('idTopic', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statuscode', sa.String(length=10), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topicname', sa.String(length=50), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('playground')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playground',
    sa.Column('equip_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('install_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.CheckConstraint("(location)::text = ANY ((ARRAY['north'::character varying, 'south'::character varying, 'west'::character varying, 'east'::character varying, 'northeast'::character varying, 'southeast'::character varying, 'southwest'::character varying, 'northwest'::character varying])::text[])", name='playground_location_check'),
    sa.PrimaryKeyConstraint('equip_id', name='playground_pkey')
    )
    op.drop_table('topics')
    op.drop_table('status')
    op.drop_table('newstopic')
    op.drop_table('news')
    # ### end Alembic commands ###
