"""empty message

Revision ID: 5508088536db
Revises: 2f44fe6e73f0
Create Date: 2018-10-10 22:38:39.062012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5508088536db'
down_revision = '2f44fe6e73f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('title', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'title')
    # ### end Alembic commands ###
